# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path


name: Unittest

on:
  push:
  workflow_dispatch:


jobs:
  test:
    name: Unittest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set Configuration
      - name: Set Config
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: 'flevents-backend/src/main/resources/application.properties'
          property: |
            'spring.datasource.url'
            'spring.datasource.username'
            'spring.datasource.password'
            'spring.jpa.hibernate.ddl-auto'
            'spring.datasource.driverClassName'
            'spring.jpa.properties.hibernate.dialect'
            'spring.mail.host'
            'spring.mail.port'
            'spring.mail.username'
            'spring.mail.password'
            'spring.mail.properties.mail.smtp.auth'
            'spring.mail.properties.mail.smtp.starttls.enable'
            'mail.smtp.ssl.protocols'
            'spring.datasource.hikari.auto-commit'
            'application.organizationjoinurl'
            'application.eventjoinurl'
            'server.port'
            'application.baseurl'
            'application.jwtSecret'
            'application.jwtExpirationMs'
          value: |
            'jdbc:postgresql://localhost:5432/flevents'
            'postgres'
            '${{secrets.DBSECRETPRD}}'
            'update'
            'org.postgresql.Driver'
            'org.hibernate.dialect.PostgreSQLDialect'
            'smtp.ionos.de'
            '587'
            'info@flyndre.de'
            '${{secrets.MAILSECRETPRD}}'
            'true'
            'true'
            'false'
            'http:flevents.flyndre.de:8080'
            '8082'
            '${{secrets.JWTSECRET}}'
            '6300000'
               
            - name: Set Config
            uses: christian-draeger/write-properties@1.1.0
            with:
              path: 'flevents-backend/src/main/resources/application-integration.properties'
              property: |
                'spring.datasource.url'
                'spring.datasource.username'
                'spring.datasource.password'
                'spring.jpa.hibernate.ddl-auto'
                'spring.datasource.driverClassName'
                'spring.jpa.properties.hibernate.dialect'
                'spring.mail.host'
                'spring.mail.port'
                'spring.mail.username'
                'spring.mail.password'
                'spring.mail.properties.mail.smtp.auth'
                'spring.mail.properties.mail.smtp.starttls.enable'
                'mail.smtp.ssl.protocols'
                'spring.datasource.hikari.auto-commit'
                'application.organizationjoinurl'
                'application.eventjoinurl'
                'server.port'
                'application.baseurl'
                'application.jwtSecret'
                'application.jwtExpirationMs'
              value: |
                'jdbc:postgresql://localhost:5432/flevents'
                'postgres'
                '${{secrets.DBSECRETPRD}}'
                'update'
                'org.postgresql.Driver'
                'org.hibernate.dialect.PostgreSQLDialect'
                'smtp.ionos.de'
                '587'
                'info@flyndre.de'
                '${{secrets.MAILSECRETPRD}}'
                'true'
                'true'
                'false'
                'http:flevents.flyndre.de:8080'
                '8082'
                '${{secrets.JWTSECRET}}'
                '6300000'
      #Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/flevents-backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Test the application using Maven
      - name: Test with Maven
        run: mvn -Dtest=FleventsBackendApplicationTests test --file flevents-backend/pom.xml
      #Test the application using Maven - all Tests
      - name: Test with Maven - all
        run: mvn test --file flevents-backend/pom.xml

  build:
    name: Build Artifact
    needs: test
      
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set Configuration
      - name: Set Config
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: 'flevents-backend/src/main/resources/application.properties'
          property: |
            'spring.datasource.url'
            'spring.datasource.username'
            'spring.datasource.password'
            'spring.jpa.hibernate.ddl-auto'
            'spring.datasource.driverClassName'
            'spring.jpa.properties.hibernate.dialect'
            'spring.mail.host'
            'spring.mail.port'
            'spring.mail.username'
            'spring.mail.password'
            'spring.mail.properties.mail.smtp.auth'
            'spring.mail.properties.mail.smtp.starttls.enable'
            'mail.smtp.ssl.protocols'
            'spring.datasource.hikari.auto-commit'
            'application.organizationjoinurl'
            'application.eventjoinurl'
            'server.port'
            'application.baseurl'
            'application.jwtSecret'
            'application.jwtExpirationMs'
          value: |
            'jdbc:postgresql://localhost:5432/flevents'
            'postgres'
            '${{secrets.DBSECRETPRD}}'
            'update'
            'org.postgresql.Driver'
            'org.hibernate.dialect.PostgreSQLDialect'
            'smtp.ionos.de'
            '587'
            'info@flyndre.de'
            '${{secrets.MAILSECRETPRD}}'
            'true'
            'true'
            'false'
            'http:flevents.flyndre.de:8080'
            '8082'
            '${{secrets.JWTSECRET}}'
            '6300000'
               
      #Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/flevents-backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package -DskipTests --file flevents-backend/pom.xml
      
      - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v2
        with:
          #Set artifact name
          name: artifact
          #From this path
          path: flevents-backend/target/flevents-backend-0.0.1-SNAPSHOT.jar
